actions:
  cache-font: fc-cache -f -v
  reload-xresources: xrdb ~/.Xresources
  vundle-refresh: vim +VundleClean! +VundleInstall +VundleInstall! +qall
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    actions:
    - vundle-refresh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    actions:
    - reload-xresources
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  f_inconsolata-regular.ttf:
    src: fonts/Inconsolata-Regular/Inconsolata-Regular.ttf
    dst: ~/.fonts/Inconsolata-Regular/Inconsolata-Regular.ttf
    actions:
    - cache-font
  f_gdbinit:
    src: gdbinit
    dst: ~/.gdbinit
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
profiles:
  laptop:
    include:
    - bash
    - vim
    - x11
    - i3
    - font
    - git
    - gdb
  workstation:
    include:
    - bash
    - vim
    - x11
    - i3
    - font
    - git
    - gdb
  minimal:
    include:
    - bash
    - vim

  # Packages to be used above
  bash:
    dotfiles:
    - f_bashrc
  vim:
    dotfiles:
    - f_vimrc
  x11:
    dotfiles:
    - f_xresources
    - f_xinitrc
  i3:
    dotfiles:
    - f_config
    - f_i3status_config
  font:
    dotfiles:
    - f_inconsolata-regular.ttf
  git:
    dotfiles:
    - f_gitconfig
  gdb:
    dotfiles:
    - f_gdbinit
