config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
profiles:
  default:
    dotfiles:
    - f_bashrc
    - f_vimrc
    - f_gitconfig
