actions:
  pre:
    vundle-install: test -e ~/.vim/bundle/Vundle.vim || (mkdir -p ~/.vim/bundle; git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim )
  vundle-refresh: vim +VundleClean +VundleInstall +qall
  font-cache: fc-cache -f -v
  xresources-reload: xrdb ~/.Xresources
config:
  backup: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_zshhighlighting:
    src: zsh-highlighting
    dst: ~/.zsh-highlighting
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
    actions:
    - vundle-install
    - vundle-refresh
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_i3:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_i3status:
    src: config/i3/i3status
    dst: ~/.config/i3status/config
  d_fonts:
    src: fonts
    dst: ~/.local/share/fonts
    actions:
    - font-cache
  f_picom:
    src: config/picom.conf
    dst: ~/.config/picom.conf
  f_tmux:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_tmux_themes:
    src: tmux/themes
    dst: ~/.tmux/themes
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  f_dunst:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_rofi:
    src: config/rofi/config.rasi
    dst: ~/.config/rofi/config.rasi
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  d_scripts:
    src: scripts
    dst: ~/scripts
  f_alacritty:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml

profiles:
  laptop:
    include:
    - zsh
    - zshhighlighting
    - vim
    - i3
    - x11
    - font
    - picom
    - tmux
    - polybar
    - dunst
    - rofi
    - ranger
    - dir_colors
    - scripts
    - alacritty
  sub-win:
    include:
    - zsh
    - vim
    - tmux
    - ranger
    - dir_colors
    - scripts
  work:
    include:
    - zsh
    - vim
    - x11
    - i3
    - font
    - picom
    - tmux
    - dir_colors
    - scripts
  dev:
    include:
    - zsh
    - vim
    - tmux

 # Packages to be used above
  zsh:
    dotfiles:
    - f_zshrc
  zshhighlighting:
    dotfiles:
    - f_zshhighlighting
  vim:
    dotfiles:
    - f_vimrc
  x11:
    dotfiles:
    - f_xresources
  i3:
    dotfiles:
    - f_i3
    - f_i3status
  font:
    dotfiles:
    - d_fonts
  picom:
    dotfiles:
    - f_picom
  tmux:
    dotfiles:
    - f_tmux
  polybar:
    dotfiles:
    - d_polybar
  dunst:
    dotfiles:
    - f_dunst
  rofi:
    dotfiles:
    - f_rofi
  ranger:
    dotfiles:
    - d_ranger
  dir_colors:
    dotfiles:
    - f_dir_colors
  scripts:
    dotfiles:
    - d_scripts
  alacritty:
    dotfiles:
    - f_alacritty
