actions:
  pre:
    vundle-install: test -e ~/.vim/bundle/Vundle.vim || (mkdir -p ~/.vim/bundle; git
      clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim )
  vundle-refresh: vim +VundleClean! +VundleInstall +VundleInstall! +qall
  font-cache: fc-cache -f -v
  xresources-reload: xrdb ~/.Xresources
config:
  backup: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_zshrc:
    src: zsh/zshrc
    dst: ~/.zshrc
  d_ohmyzsh:
    src: zsh/ohmyzsh
    dst: ~/.ohmyzsh
  f_zsh_themes:
    src: zsh/zsh.themes
    dst: ~/.ohmyzsh/themes
  f_vimrc:
    src: vim/vimrc
    dst: ~/.vimrc
    actions:
    - vundle-install
    - vundle-refresh
  f_xresources:
    src: X11/Xresources
    dst: ~/.Xresources
  d_xresources_themes:
    src: X11/Xresources.themes
    dst: ~/.Xresources.themes
  f_xinitrc:
    src: X11/xinitrc
    dst: ~/.xinitrc
  f_i3:
    src: i3/config
    dst: ~/.config/i3/config
  f_i3status:
    src: i3/i3status
    dst: ~/.config/i3status/config
  d_fonts:
    src: fonts
    dst: ~/.local/share/fonts
    actions:
    - font-cache
  f_compton:
    src: compton/compton.conf
    dst: ~/.config/compton.conf
  f_tmux:
    src: tmux/tmux.conf
    dst: ~/.tmux.conf
  d_tmux_themes:
    src: tmux/themes
    dst: ~/.tmux/themes
  d_polybar:
    src: polybar
    dst: ~/.config/polybar
  d_dunst:
    src: dunst
    dst: ~/.config/dunst
  d_rofi:
    src: rofi
    dst: ~/.config/rofi
  d_cava:
    src: cava
    dst: ~/.config/cava
  d_neofetch:
    src: neofetch
    dst: ~/.config/neofetch
  d_ranger:
    src: ranger
    dst: ~/.config/ranger
  f_dir_colors:
    src: dir_colors/dir_colors
    dst: ~/.dir_colors
  d_scripts:
    src: scripts
    dst: ~/scripts

profiles:
  laptop:
    include:
    - zsh
    - vim
    - x11
    - i3
    - font
    - compton
    - tmux
    - polybar
    - dunst
    - rofi
    - cava
    - neofetch
    - ranger
    - dir_colors
    - scripts
  sub-win:
    include:
    - zsh
    - vim
    - tmux
    - ranger
    - neofetch
    - dir_colors
    - scripts
  work:
    include:
    - zsh
    - vim
    - x11
    - i3
    - font
    - compton
    - tmux
    - dir_colors
    - scripts
  dev:
    include:
    - vim
    - tmux

 # Packages to be used above
  bash:
    dotfiles:
    - f_bashrc
  zsh:
    dotfiles:
    - f_zshrc
    - d_ohmyzsh
    - f_zsh_themes
  vim:
    dotfiles:
    - f_vimrc
  x11:
    dotfiles:
    - f_xresources
    - d_xresources_themes
    - f_xinitrc
  i3:
    dotfiles:
    - f_i3
    - f_i3status
  font:
    dotfiles:
    - d_fonts
  compton:
    dotfiles:
    - f_compton
  tmux:
    dotfiles:
    - f_tmux
    - d_tmux_themes
  polybar:
    dotfiles:
    - d_polybar
  dunst:
    dotfiles:
    - d_dunst
  rofi:
    dotfiles:
    - d_rofi
  cava:
    dotfiles:
    - d_cava
  neofetch:
    dotfiles:
    - d_neofetch
  ranger:
    dotfiles:
    - d_ranger
  dir_colors:
    dotfiles:
    - f_dir_colors
  scripts:
    dotfiles:
    - d_scripts
