config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
profiles:
  default:
    dotfiles:
    - f_bashrc
    - f_vimrc
