config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
profiles:
  default:
    dotfiles:
    - f_bashrc
    - f_vimrc
    - f_gitconfig
    - f_xresources
    - f_config
