config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_i3status_config:
    src: config/i3status/config
    dst: ~/.config/i3status/config
  f_inconsolata-regular.ttf:
    src: fonts/Inconsolata-Regular/Inconsolata-Regular.ttf
    dst: ~/.fonts/Inconsolata-Regular/Inconsolata-Regular.ttf
  f_gdbinit:
    src: gdbinit
    dst: ~/.gdbinit
profiles:
  default:
    dotfiles:
    - f_bashrc
    - f_vimrc
    - f_gitconfig
    - f_xresources
    - f_config
    - f_i3status_config
    - f_inconsolata-regular.ttf
    - f_gdbinit
